improved description
razvancir96/itschool-students-gen2 pull request #5
Opened 2022-04-07 13:51 UTC by bvlucretiu

That test change in the lesson with "Mersi"

2022-04-09 14:46 UTC, razvancir96 approved these changes

2022-04-09 14:46 UTC, razvancir96 commented on index.html
> +                    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Molestiae omnis nobis quo dicta culpa eum exercitationem provident ex iure pariatur? Tempora sunt accusamus tempore modi.
Please remove this change, as it is not necessary

2022-04-09 14:46 UTC, razvancir96 commented on index.html
> +                    Quidem, corrupti perspiciatis aliquid dicta cum odio sapiente tempora quas incidunt adipisci alias praesentium et excepturi error maxime aspernatur sint qui doloremque distinctio.
Please remove this change, as it is not necessary

2022-04-09 14:46 UTC, razvancir96 commented on index.html
> +                  <a target="blank" href="https://www.linkedin.com/in/vasilebirta/"
Please remove the target="blank" attribute, as I will have to add it for all links. Thank you for pointing this out! 🙏

2022-04-09 14:46 UTC, razvancir96 commented on index.html
> +                    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Molestiae omnis nobis quo dicta culpa eum exercitationem provident ex iure pariatur? Tempora sunt accusamus tempore modi.
Please remove this change, as it is not necessary

2022-04-09 14:46 UTC, razvancir96 commented on index.html
> +                    Quidem, corrupti perspiciatis aliquid dicta cum odio sapiente tempora quas incidunt adipisci alias praesentium et excepturi error maxime aspernatur sint qui doloremque distinctio.
Please remove this change, as it is not necessary

2022-04-09 14:46 UTC, razvancir96 commented on index.html
> +                    so my goal is JavaScript!<br>
Do not use the `<br>` tag. If you want a new line, add a new `<p>` tag.

2022-04-09 14:46 UTC, razvancir96 commented on index.html
> +                    <i>"If you want to live a happy life,
It's better to use the `<em>` tag instead of `<i>`

2022-04-09 14:46 UTC, razvancir96 commented on index.html
> +                    Lifetime is a broken challenge in several episodes and IT & JavaScript is a passion that covers all other episodes especially since this passion has taken shape through the prism
`a style="text-decoration: none;" ` please remove this style, as all links should have the same style. Also, if we add style, we add it to a CSS file, not inline 😄

2022-04-09 14:46 UTC, razvancir96 commented on index.html
> +                    Lifetime is a broken challenge in several episodes and IT & JavaScript is a passion that covers all other episodes especially since this passion has taken shape through the prism
`with great passion and one of them is <strong>Răzvan Cîrlugea</strong>` The phrase becomes too long. You can split it here: `with great passion. One of them is <strong>Răzvan Cîrlugea</strong>`

2022-04-09 14:48 UTC, razvancir96 requested changes
Sorry, I've accepted the PR by mistake! Please read the comments for the requested changes

2022-04-14 16:14 UTC, razvancir96 approved these changes
Looking good now! 🚀

2022-04-14 16:14 UTC, merged

2022-04-24 18:21 UTC, bvlucretiu commented
Thanks for appreciation!